In [1]:
import pandas as pd
import numpy as np

## DATA EXPLORATION & PREPARATION

### part a

In [2]:
df= pd.read_csv('train.csv')     #creating dataframe for train datas
train_x_a = df.drop("SalePrice",1)    #SalePrice column is dropped
train_y = pd.DataFrame(df["SalePrice"])   #creating new dataframe for SalePrice column

In [3]:
train_x_a.head(20)

,MSSubClass,LotFrontage,LotArea,Street,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,...,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,MoSold
0,60,65.0,8450,Pave,7,5,196.0,706,150,856,...,0,2,1,3,1,8,0,2,548,2
1,20,80.0,9600,Pave,6,8,0.0,978,284,1262,...,1,2,0,3,1,6,1,2,460,5
2,60,68.0,11250,Pave,7,5,162.0,486,434,920,...,0,2,1,3,1,6,1,2,608,9
3,70,60.0,9550,Pave,7,5,0.0,216,540,756,...,0,1,0,3,1,7,1,3,642,2
4,60,84.0,14260,Pave,8,5,350.0,655,490,1145,...,0,2,1,4,1,9,1,3,836,12
5,50,85.0,14115,Pave,5,5,0.0,732,64,796,...,0,1,1,1,1,5,0,2,480,10
6,20,75.0,10084,Pave,8,5,186.0,1369,317,1686,...,0,2,0,3,1,7,1,2,636,8
7,60,NaN,10382,Pave,7,6,240.0,859,216,1107,...,0,2,1,3,1,7,2,2,484,11
8,50,51.0,6120,Pave,7,5,0.0,0,952,952,...,0,2,0,2,2,8,2,2,468,4
9,190,50.0,7420,Pave,5,6,0.0,851,140,991,...,0,1,0,2,2,5,2,1,205,1
10,20,70.0,11200,Pave,5,5,0.0,906,134,1040,...,0,1,0,3,1,5,0,1,384,2
11,60,85.0,11924,Pave,9,5,286.0,998,177,1175,...,0,3,0,4,1,11,2,3,736,7
12,20,NaN,12968,Pave,5,6,0.0,737,175,912,...,0,1,0,2,1,4,0,1,352,9
13,20,91.0,10652,Pave,7,5,306.0,0,1494,1494,...,0,2,0,3,1,7,1,3,840,8
14,20,NaN,10920,Pave,6,5,212.0,733,520,1253,...,0,1,1,2,1,5,1,1,352,5
15,45,51.0,6120,Pave,7,8,0.0,0,832,832,...,0,1,0,2,1,5,0,2,576,7
16,20,NaN,11241,Pave,6,7,180.0,578,426,1004,...,0,1,0,2,1,5,1,2,480,3
17,90,72.0,10791,Pave,4,5,0.0,0,0,0,...,0,2,0,2,2,6,0,2,516,10
18,20,66.0,13695,Pave,5,5,0.0,646,468,1114,...,0,1,1,3,1,6,0,2,576,6
19,20,70.0,7560,Pave,5,6,0.0,504,525,1029,...,0,1,0,3,1,6,0,1,294,5

In [4]:
train_y.head(20)

    SalePrice
0      208500
1      181500
2      223500
3      140000
4      250000
5      143000
6      307000
7      200000
8      129900
9      118000
10     129500
11     345000
12     144000
13     279500
14     157000
15     132000
16     149000
17      90000
18     159000
19     139000

### part b

In [5]:
nan_columns = train_x_a.columns[train_x_a.isnull().any()].tolist()   #finding column names which have missing values
median_val={}      #dictionary for nan columns and their median values to use later
for i in nan_columns:
    median = train_x_a[i].median()   #median of the column
    median_val[i]=median
    train_x_a[i].fillna(median, inplace=True)    #filling the missing value cells with median of the column
train_x_b=train_x_a 
print (median_val)

{'LotFrontage': 70.0, 'MasVnrArea': 0.0}

In [6]:
print(nan_columns)

['LotFrontage', 'MasVnrArea']

In [7]:
train_x_b.head(20)

,MSSubClass,LotFrontage,LotArea,Street,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,...,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,MoSold
0,60,65.0,8450,Pave,7,5,196.0,706,150,856,...,0,2,1,3,1,8,0,2,548,2
1,20,80.0,9600,Pave,6,8,0.0,978,284,1262,...,1,2,0,3,1,6,1,2,460,5
2,60,68.0,11250,Pave,7,5,162.0,486,434,920,...,0,2,1,3,1,6,1,2,608,9
3,70,60.0,9550,Pave,7,5,0.0,216,540,756,...,0,1,0,3,1,7,1,3,642,2
4,60,84.0,14260,Pave,8,5,350.0,655,490,1145,...,0,2,1,4,1,9,1,3,836,12
5,50,85.0,14115,Pave,5,5,0.0,732,64,796,...,0,1,1,1,1,5,0,2,480,10
6,20,75.0,10084,Pave,8,5,186.0,1369,317,1686,...,0,2,0,3,1,7,1,2,636,8
7,60,70.0,10382,Pave,7,6,240.0,859,216,1107,...,0,2,1,3,1,7,2,2,484,11
8,50,51.0,6120,Pave,7,5,0.0,0,952,952,...,0,2,0,2,2,8,2,2,468,4
9,190,50.0,7420,Pave,5,6,0.0,851,140,991,...,0,1,0,2,2,5,2,1,205,1
10,20,70.0,11200,Pave,5,5,0.0,906,134,1040,...,0,1,0,3,1,5,0,1,384,2
11,60,85.0,11924,Pave,9,5,286.0,998,177,1175,...,0,3,0,4,1,11,2,3,736,7
12,20,70.0,12968,Pave,5,6,0.0,737,175,912,...,0,1,0,2,1,4,0,1,352,9
13,20,91.0,10652,Pave,7,5,306.0,0,1494,1494,...,0,2,0,3,1,7,1,3,840,8
14,20,70.0,10920,Pave,6,5,212.0,733,520,1253,...,0,1,1,2,1,5,1,1,352,5
15,45,51.0,6120,Pave,7,8,0.0,0,832,832,...,0,1,0,2,1,5,0,2,576,7
16,20,70.0,11241,Pave,6,7,180.0,578,426,1004,...,0,1,0,2,1,5,1,2,480,3
17,90,72.0,10791,Pave,4,5,0.0,0,0,0,...,0,2,0,2,2,6,0,2,516,10
18,20,66.0,13695,Pave,5,5,0.0,646,468,1114,...,0,1,1,3,1,6,0,2,576,6
19,20,70.0,7560,Pave,5,6,0.0,504,525,1029,...,0,1,0,3,1,6,0,1,294,5

### part c

In [8]:
train_x_b_num = train_x_b.select_dtypes(include=[np.number])     #finding column names which contain numerical values
categorical_columns=list(set(train_x_b.columns) - set(train_x_b_num))    #finding categorical column names by subtracting numerical column names from all column names

In [9]:
print(categorical_columns)

['Street']

### part d

In [10]:
from sklearn.preprocessing import OneHotEncoder
train_x_b_cat=train_x_b[categorical_columns]     
cat_encoder = OneHotEncoder(categories="auto")
train_x_b_cat_1hot = cat_encoder.fit_transform(train_x_b_cat)   #converting the categorical values to numerical ones in order to use in predictions
train_x_b["Street"]=train_x_b_cat_1hot.toarray()    
train_x_d = train_x_b

In [11]:
train_x_d

,MSSubClass,LotFrontage,LotArea,Street,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,...,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,MoSold
0,60,65.0,8450,0.0,7,5,196.0,706,150,856,...,0,2,1,3,1,8,0,2,548,2
1,20,80.0,9600,0.0,6,8,0.0,978,284,1262,...,1,2,0,3,1,6,1,2,460,5
2,60,68.0,11250,0.0,7,5,162.0,486,434,920,...,0,2,1,3,1,6,1,2,608,9
3,70,60.0,9550,0.0,7,5,0.0,216,540,756,...,0,1,0,3,1,7,1,3,642,2
4,60,84.0,14260,0.0,8,5,350.0,655,490,1145,...,0,2,1,4,1,9,1,3,836,12
5,50,85.0,14115,0.0,5,5,0.0,732,64,796,...,0,1,1,1,1,5,0,2,480,10
6,20,75.0,10084,0.0,8,5,186.0,1369,317,1686,...,0,2,0,3,1,7,1,2,636,8
7,60,70.0,10382,0.0,7,6,240.0,859,216,1107,...,0,2,1,3,1,7,2,2,484,11
8,50,51.0,6120,0.0,7,5,0.0,0,952,952,...,0,2,0,2,2,8,2,2,468,4
9,190,50.0,7420,0.0,5,6,0.0,851,140,991,...,0,1,0,2,2,5,2,1,205,1
10,20,70.0,11200,0.0,5,5,0.0,906,134,1040,...,0,1,0,3,1,5,0,1,384,2
11,60,85.0,11924,0.0,9,5,286.0,998,177,1175,...,0,3,0,4,1,11,2,3,736,7
12,20,70.0,12968,0.0,5,6,0.0,737,175,912,...,0,1,0,2,1,4,0,1,352,9
13,20,91.0,10652,0.0,7,5,306.0,0,1494,1494,...,0,2,0,3,1,7,1,3,840,8
14,20,70.0,10920,0.0,6,5,212.0,733,520,1253,...,0,1,1,2,1,5,1,1,352,5
15,45,51.0,6120,0.0,7,8,0.0,0,832,832,...,0,1,0,2,1,5,0,2,576,7
16,20,70.0,11241,0.0,6,7,180.0,578,426,1004,...,0,1,0,2,1,5,1,2,480,3
17,90,72.0,10791,0.0,4,5,0.0,0,0,0,...,0,2,0,2,2,6,0,2,516,10
18,20,66.0,13695,0.0,5,5,0.0,646,468,1114,...,0,1,1,3,1,6,0,2,576,6
19,20,70.0,7560,0.0,5,6,0.0,504,525,1029,...,0,1,0,3,1,6,0,1,294,5
20,60,101.0,14215,0.0,8,5,380.0,0,1158,1158,...,0,3,1,4,1,9,1,3,853,11
21,45,57.0,7449,0.0,7,7,0.0,0,637,637,...,0,1,0,3,1,6,1,1,280,6
22,20,75.0,9742,0.0,8,5,281.0,0,1777,1777,...,0,2,0,3,1,7,1,2,534,9
23,120,44.0,4224,0.0,5,7,0.0,840,200,1040,...,0,1,0,3,1,6,1,2,572,6
24,20,70.0,8246,0.0,5,8,0.0,188,204,1060,...,0,1,0,3,1,6,1,1,270,5
25,20,110.0,14230,0.0,8,5,640.0,0,1566,1566,...,0,2,0,3,1,7,1,3,890,7
26,20,60.0,7200,0.0,5,7,0.0,234,180,900,...,1,1,0,3,1,5,0,2,576,5
27,20,98.0,11478,0.0,8,5,200.0,1218,486,1704,...,0,2,0,3,1,7,1,3,772,5
28,20,47.0,16321,0.0,5,6,0.0,1277,207,1484,...,0,1,0,2,1,6,2,1,319,12
29,30,60.0,6324,0.0,4,6,0.0,0,520,520,...,0,1,0,1,1,4,0,1,240,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,50,60.0,10800,0.0,4,4,0.0,0,720,720,...,0,1,1,4,1,6,0,0,0,12
971,160,36.0,2268,0.0,7,5,106.0,567,197,764,...,0,2,0,2,1,6,0,2,474,7
972,120,55.0,7892,0.0,6,5,0.0,0,918,918,...,0,2,0,2,1,5,1,1,264,4
973,20,95.0,11639,0.0,7,5,0.0,0,1428,1428,...,0,2,0,3,1,6,0,2,480,12
974,70,60.0,11414,0.0,7,8,0.0,0,728,728,...,0,1,0,3,1,8,0,2,532,10
975,160,70.0,2651,0.0,7,5,0.0,641,32,673,...,0,2,1,3,1,6,0,2,490,4
976,30,51.0,5900,0.0,4,7,0.0,0,440,440,...,0,1,0,2,1,4,0,0,0,8
977,120,35.0,4274,0.0,7,5,0.0,1106,135,1241,...,0,1,1,1,1,4,0,2,569,11
978,20,68.0,9450,0.0,4,5,0.0,552,342,894,...,0,1,0,3,1,5,0,2,400,5
979,20,80.0,8816,0.0,5,6,0.0,651,470,1121,...,0,1,0,3,1,5,0,2,480,6
980,85,70.0,12122,0.0,7,9,210.0,867,77,944,...,0,1,0,3,1,6,0,2,588,7
981,60,98.0,12203,0.0,8,5,975.0,854,371,1225,...,0,2,1,4,1,8,1,3,676,7
982,20,43.0,3182,0.0,7,5,16.0,0,1266,1266,...,0,2,0,2,1,6,1,2,388,3
983,60,70.0,11250,0.0,8,5,0.0,0,1128,1128,...,0,2,1,4,1,9,1,2,779,5
984,90,75.0,10125,0.0,5,5,0.0,0,0,0,...,0,2,0,4,2,8,0,2,539,8
985,190,68.0,10880,0.0,5,5,0.0,1040,124,1164,...,0,1,0,3,1,5,0,1,240,8
986,50,59.0,5310,0.0,6,8,0.0,0,485,485,...,0,1,0,2,1,5,0,1,255,6
987,20,83.0,10159,0.0,9,5,450.0,1646,284,1930,...,0,2,1,3,1,8,1,3,606,4
988,60,70.0,12046,0.0,6,6,298.0,156,692,848,...,0,2,1,4,1,8,1,2,551,6
989,60,65.0,8125,0.0,7,5,0.0,0,770,770,...,0,2,1,3,1,6,0,2,614,8
990,60,82.0,9452,0.0,8,5,423.0,1074,322,1396,...,0,2,1,3,1,7,1,3,870,6
991,70,121.0,17671,0.0,8,9,0.0,216,700,916,...,0,1,1,4,1,8,1,2,424,11
992,60,80.0,9760,0.0,6,8,340.0,536,169,822,...,0,2,1,3,1,7,1,2,440,7
993,60,68.0,8846,0.0,6,5,0.0,0,750,750,...,0,2,1,3,1,6,0,2,564,8
994,20,96.0,12456,0.0,10,5,230.0,1172,528,1700,...,0,2,0,3,1,7,1,3,786,7
995,50,51.0,4712,0.0,4,7,0.0,384,363,747,...,0,1,1,3,1,5,0,1,305,8
996,20,70.0,10659,0.0,5,6,0.0,915,135,1050,...,0,1,0,3,1,6,0,1,368,1
997,20,70.0,11717,0.0,6,6,571.0,0,1442,1442,...,0,2,0,2,1,6,1,2,615,2
998,30,60.0,9786,0.0,3,4,0.0,0,1007,1007,...,0,1,0,3,1,6,1,1,210,5
999,20,64.0,6762,0.0,7,5,24.0,686,501,1187,...,0,2,0,2,1,6,0,2,632,2

### part e

In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
train_x_d=scaler.fit_transform(train_x_d)     #scaling values of train dataframe  
train_x_e = pd.DataFrame(data=train_x_d, columns=train_x_b.columns)    #creating new dataframe from scaled values array

c:\python37\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
c:\python37\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [13]:
train_x_e.head(2)

,MSSubClass,LotFrontage,LotArea,Street,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,...,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,MoSold
0,0.073872,-0.235351,-0.196474,-0.063372,0.632900,-0.529618,0.464035,0.589782,-0.939672,-0.486827,...,-0.239522,0.787603,1.230454,0.178216,-0.208547,0.935889,-0.939129,0.316364,0.357524,-1.601265
1,-0.873204,0.475965,-0.095659,-0.063372,-0.090414,2.177118,-0.576236,1.204925,-0.638291,0.475863,...,3.890171,0.787603,-0.773542,0.178216,-0.208547,-0.307817,0.600426,0.316364,-0.063938,-0.485919

## LINEAR REGRESSION TO PREDICT HOUSE PRICES

### part f

In [14]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()       
lr_model.fit(train_x_e,train_y)     #performing linear regression for predicting numeric response

from sklearn.metrics import mean_squared_error

SalePrice_predictions = lr_model.predict(train_x_e)
lin_mse = mean_squared_error(train_y, SalePrice_predictions)     #performing mean squared error to find prediction errors
lin_rmse = np.sqrt(lin_mse)
lin_rmse

32276.837405211583

### part g

In [15]:
from sklearn.model_selection import cross_val_score
train_mse_score =cross_val_score(lr_model, train_x_e, train_y,     #performing cross validation with 5 segments, evaluating the performance to find mse
                             scoring="neg_mean_squared_error", cv=5)
print(train_mse_score)

[-9.67684284e+08 -7.41103398e+08 -1.66625413e+09 -1.46841147e+09
 -8.85984650e+08]

In [16]:
average_mse = train_mse_score.mean()     #average mse for 5 fold cross validation
print(average_mse)

-1145887585.6332068

### part h

In [17]:
df2=pd.read_csv('test.csv')     #creating dataframe from test data
test_x = pd.read_csv('test.csv').drop("SalePrice",1)    #dropping the SalePrice value to predict it later
test_y = pd.DataFrame(df2["SalePrice"])    #creating another dataframe from SalePrice column

In [18]:
test_x.head(2)

,MSSubClass,LotFrontage,LotArea,Street,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,...,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,MoSold
0,20,74.0,10206,Pave,3,3,0.0,0,0,0,...,0,1,0,2,1,4,0,2,528,7
1,30,60.0,5400,Pave,5,6,0.0,0,691,691,...,0,1,0,2,1,4,0,1,216,1

In [19]:
test_y.head(2)

   SalePrice
0      82000
1      86000

In [20]:
test_nan_columns = test_x.columns[test_x.isnull().any()].tolist()    #getting the names of columns which have missing values
for i in nan_columns:
    test_x[i].fillna(median_val[i], inplace=True)    #filling the missing value cells with the median which is obtained from train data

In [21]:
print(test_nan_columns)

['LotFrontage', 'MasVnrArea']

In [22]:
test_x.head(20)

,MSSubClass,LotFrontage,LotArea,Street,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,...,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,MoSold
0,20,74.0,10206,Pave,3,3,0.0,0,0,0,...,0,1,0,2,1,4,0,2,528,7
1,30,60.0,5400,Pave,5,6,0.0,0,691,691,...,0,1,0,2,1,4,0,1,216,1
2,20,75.0,11957,Pave,8,5,53.0,24,1550,1574,...,0,2,0,3,1,7,1,3,824,7
3,90,70.0,11500,Pave,5,6,164.0,0,1680,1680,...,0,2,0,4,2,8,0,2,528,6
4,120,43.0,3182,Pave,7,5,16.0,16,1330,1346,...,0,2,0,1,1,7,1,2,457,5
5,80,65.0,8385,Pave,5,8,220.0,595,390,985,...,0,2,0,3,1,6,0,1,328,11
6,20,70.0,12155,Pave,6,3,0.0,1237,420,1657,...,1,2,0,3,1,7,1,2,484,3
7,160,21.0,2217,Pave,4,4,0.0,273,0,546,...,0,1,1,3,1,6,0,1,286,8
8,20,43.0,12118,Pave,7,5,108.0,0,1710,1710,...,0,2,0,3,1,7,1,2,550,4
9,50,60.0,6000,Pave,5,5,0.0,0,1008,1008,...,0,2,0,4,1,7,0,0,0,6
10,50,115.0,21286,Pave,5,5,0.0,0,720,720,...,0,2,0,4,1,7,1,1,312,8
11,90,75.0,9825,Pave,5,5,0.0,0,0,0,...,0,2,0,4,2,8,0,0,0,5
12,70,55.0,10592,Pave,6,7,0.0,0,602,602,...,0,1,1,3,1,7,2,1,180,8
13,30,60.0,7200,Pave,5,4,0.0,247,310,1022,...,0,1,0,2,1,4,0,1,280,6
14,20,60.0,11664,Pave,6,5,206.0,336,746,1082,...,0,1,0,2,1,5,1,1,240,11
15,60,70.0,8400,Pave,8,6,0.0,643,167,810,...,0,2,1,3,1,6,0,2,528,11
16,20,73.0,11883,Pave,7,5,196.0,690,814,1504,...,0,2,0,3,1,6,1,2,478,6
17,120,70.0,5814,Pave,8,5,0.0,1036,184,1220,...,0,1,0,1,1,4,1,2,565,8
18,80,70.0,10784,Pave,7,5,76.0,0,384,384,...,0,2,1,3,1,7,1,2,402,5
19,120,43.0,3013,Pave,7,5,145.0,16,1346,1362,...,0,2,0,2,1,6,1,2,440,4

In [23]:
test_x_num = test_x.select_dtypes(include=[np.number])     #finding the column names which includes numerical data
test_x_categorical_columns=list(set(test_x.columns) - set(test_x_num))    #getting categorical columns by subtracting numerical columns from all column names

In [24]:
print(test_x_categorical_columns)

['Street']

In [25]:
test_x_cat=test_x[categorical_columns]
cat_encoder = OneHotEncoder(categories="auto")
test_x_cat_1hot = cat_encoder.fit_transform(test_x_cat)     #transforming the categorical column to numerical one
test_x["Street"]=test_x_cat_1hot.toarray()
#test_x.head(20)

In [26]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
test_x_sc=scaler.fit_transform(test_x)     #scaling the all test datas
test_x = pd.DataFrame(data=test_x_sc, columns=test_x.columns)    #converting scaled datas from array to a dataframe

c:\python37\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
c:\python37\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

### part i

In [27]:
predicted_values = lr_model.predict(test_x)   #predicting Sale Prices by using test data with linear regression

In [28]:
print(predicted_values[10:13])

[[ 2.26912512e+16]
 [-3.86254339e+16]
 [ 2.50971076e+16]]

In [29]:
test_mse_score =mean_squared_error(test_y,predicted_values)    #computing mean squared error for predicted datas
print(test_mse_score)

1.8582688347959748e+33

## CLASSIFICATION MODEL TO PREDICT HOUSE PRICE CATEGORY

### part j

In [30]:
train_y_j=train_y
for i in train_y["SalePrice"]:      #labeling the SalePrice train data specifying prices
    if i<100000:
        train_y_j=train_y_j.replace(i,1)
    elif i>=100000 and i<200000:
            train_y_j=train_y_j.replace(i,2)
    elif i>=200000 and i<300000:
        train_y_j=train_y_j.replace(i,3)
    elif i>=300000 and i<400000:
        train_y_j=train_y_j.replace(i,4)
    else:
        train_y_j=train_y_j.replace(i,5)
train_y_j.head(100)

    SalePrice
0           3
1           2
2           3
3           2
4           3
5           2
6           4
7           3
8           2
9           2
10          2
11          4
12          2
13          3
14          2
15          2
16          2
17          1
18          2
19          2
20          4
21          2
22          3
23          2
24          2
25          3
26          2
27          4
28          3
29          1
..        ...
70          3
71          2
72          2
73          2
74          2
75          1
76          2
77          2
78          2
79          2
80          2
81          2
82          3
83          2
84          2
85          3
86          2
87          2
88          1
89          2
90          2
91          1
92          2
93          2
94          3
95          2
96          3
97          1
98          1
99          2

[100 rows x 1 columns]

In [31]:
test_y_j=test_y
for i in test_y["SalePrice"]:     #labeling test SalePrice data specifying prices
    if i<100000:
        test_y_j=test_y_j.replace(i,1)
    elif i>=100000 and i<200000:
            test_y_j=test_y_j.replace(i,2)
    elif i>=200000 and i<300000:
        test_y_j=test_y_j.replace(i,3)
    elif i>=300000 and i<400000:
        test_y_j=test_y_j.replace(i,4)
    else:
        test_y_j=test_y_j.replace(i,5)
test_y_j.head(100)

    SalePrice
0           1
1           1
2           3
3           2
4           2
5           2
6           2
7           1
8           3
9           2
10          2
11          2
12          2
13          1
14          2
15          3
16          3
17          2
18          2
19          3
20          2
21          2
22          1
23          2
24          3
25          2
26          2
27          3
28          2
29          2
..        ...
70          2
71          2
72          1
73          2
74          2
75          3
76          2
77          2
78          2
79          2
80          2
81          2
82          2
83          2
84          2
85          2
86          1
87          3
88          2
89          2
90          1
91          2
92          2
93          2
94          2
95          2
96          2
97          2
98          2
99          2

[100 rows x 1 columns]

In [32]:
train_y_j.head(2)

   SalePrice
0          3
1          2

In [33]:
test_y_j.head(2)

   SalePrice
0          1
1          1

### part k

In [34]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=42)      #performing random forest classifier for train datas
model.fit(train_x_e, train_y_j)

c:\python37\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\python37\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

### part l

In [37]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
y_train_pred = cross_val_predict(model, train_x_e, train_y_j["SalePrice"], cv=5)    #performing 5 fold cross validation with train data using random forest classifer

In [38]:
accuracy =accuracy_score(train_y_j, y_train_pred)     #computing accuracy score, precision, recall, f1 score and confusion matrix for predicted values
precision = precision_score(train_y_j, y_train_pred, average="micro")
recall = recall_score(train_y_j, y_train_pred, average="micro")
f1 = f1_score(train_y_j, y_train_pred, average="micro")
confusion_matrix =confusion_matrix(train_y_j["SalePrice"], y_train_pred)

In [39]:
print(confusion_matrix)
print("accuracy: {}\nprecision: {}\nrecall: {}\nf1: {}".format(accuracy,precision,recall,f1))

[[ 37  39   1   0   0]
 [ 19 568  25   1   1]
 [  0  63 149   8   1]
 [  0   2  32  30   3]
 [  0   0   4  12   5]]
accuracy: 0.789
precision: 0.789
recall: 0.789
f1: 0.7890000000000001

### part m

In [40]:
predicted_values = model.predict(test_x)    #predicting Sale Prices by using test data with random forest classifier

In [41]:
print(predicted_values[20:23])

[2 2 2]

In [42]:
from sklearn.metrics import confusion_matrix as cm     #importing confusion matrix as cm to not get the confusion matrix from above
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(test_y_j, predicted_values)   #computing accuracy score, precision, recall, f1 score and confusion matrix for predicted values
precision = precision_score(test_y_j, predicted_values, average="micro")
recall = recall_score(test_y_j, predicted_values, average="micro")
f1 = f1_score(test_y_j,predicted_values, average="micro")
confusion_matrix =cm(test_y_j, predicted_values)

In [43]:
print(confusion_matrix)
print("accuracy: {}\nprecision: {}\nrecall: {}\nf1: {}".format(accuracy,precision,recall,f1))

[[ 19  18   0   0   0]
 [  2 281  11   2   1]
 [  0  24  68   6   1]
 [  0   0  14   5   1]
 [  0   0   0   2   5]]
accuracy: 0.8217391304347826
precision: 0.8217391304347826
recall: 0.8217391304347826
f1: 0.8217391304347826